//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcScribe.StruktMain {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="StruktMain.StruktMainSoap")]
    public interface StruktMainSoap {
        
        // CODEGEN: Generating message contract since element name strWorkflowID from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/selectWorkflow", ReplyAction="*")]
        ProcScribe.StruktMain.selectWorkflowResponse selectWorkflow(ProcScribe.StruktMain.selectWorkflowRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/selectWorkflow", ReplyAction="*")]
        System.Threading.Tasks.Task<ProcScribe.StruktMain.selectWorkflowResponse> selectWorkflowAsync(ProcScribe.StruktMain.selectWorkflowRequest request);
        
        // CODEGEN: Generating message contract since element name addWorkflowResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/addWorkflow", ReplyAction="*")]
        ProcScribe.StruktMain.addWorkflowResponse addWorkflow(ProcScribe.StruktMain.addWorkflowRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/addWorkflow", ReplyAction="*")]
        System.Threading.Tasks.Task<ProcScribe.StruktMain.addWorkflowResponse> addWorkflowAsync(ProcScribe.StruktMain.addWorkflowRequest request);
        
        // CODEGEN: Generating message contract since element name strWorkflow from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/editWorkflow", ReplyAction="*")]
        ProcScribe.StruktMain.editWorkflowResponse editWorkflow(ProcScribe.StruktMain.editWorkflowRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/editWorkflow", ReplyAction="*")]
        System.Threading.Tasks.Task<ProcScribe.StruktMain.editWorkflowResponse> editWorkflowAsync(ProcScribe.StruktMain.editWorkflowRequest request);
        
        // CODEGEN: Generating message contract since element name strWorkflowID from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/deleteWorkflow", ReplyAction="*")]
        ProcScribe.StruktMain.deleteWorkflowResponse deleteWorkflow(ProcScribe.StruktMain.deleteWorkflowRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/deleteWorkflow", ReplyAction="*")]
        System.Threading.Tasks.Task<ProcScribe.StruktMain.deleteWorkflowResponse> deleteWorkflowAsync(ProcScribe.StruktMain.deleteWorkflowRequest request);
        
        // CODEGEN: Generating message contract since element name strTaskID from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/selectTask", ReplyAction="*")]
        ProcScribe.StruktMain.selectTaskResponse selectTask(ProcScribe.StruktMain.selectTaskRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/selectTask", ReplyAction="*")]
        System.Threading.Tasks.Task<ProcScribe.StruktMain.selectTaskResponse> selectTaskAsync(ProcScribe.StruktMain.selectTaskRequest request);
        
        // CODEGEN: Generating message contract since element name strTaskObject from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/addTask", ReplyAction="*")]
        ProcScribe.StruktMain.addTaskResponse addTask(ProcScribe.StruktMain.addTaskRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/addTask", ReplyAction="*")]
        System.Threading.Tasks.Task<ProcScribe.StruktMain.addTaskResponse> addTaskAsync(ProcScribe.StruktMain.addTaskRequest request);
        
        // CODEGEN: Generating message contract since element name strTask from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/editTask", ReplyAction="*")]
        ProcScribe.StruktMain.editTaskResponse editTask(ProcScribe.StruktMain.editTaskRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/editTask", ReplyAction="*")]
        System.Threading.Tasks.Task<ProcScribe.StruktMain.editTaskResponse> editTaskAsync(ProcScribe.StruktMain.editTaskRequest request);
        
        // CODEGEN: Generating message contract since element name strTaskID from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/deleteTask", ReplyAction="*")]
        ProcScribe.StruktMain.deleteTaskResponse deleteTask(ProcScribe.StruktMain.deleteTaskRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/deleteTask", ReplyAction="*")]
        System.Threading.Tasks.Task<ProcScribe.StruktMain.deleteTaskResponse> deleteTaskAsync(ProcScribe.StruktMain.deleteTaskRequest request);
        
        // CODEGEN: Generating message contract since element name selectTaskProcessAllResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/selectTaskProcessAll", ReplyAction="*")]
        ProcScribe.StruktMain.selectTaskProcessAllResponse selectTaskProcessAll(ProcScribe.StruktMain.selectTaskProcessAllRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/selectTaskProcessAll", ReplyAction="*")]
        System.Threading.Tasks.Task<ProcScribe.StruktMain.selectTaskProcessAllResponse> selectTaskProcessAllAsync(ProcScribe.StruktMain.selectTaskProcessAllRequest request);
        
        // CODEGEN: Generating message contract since element name strParentWorkflowID from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/selectTaskByParentWorkflowID", ReplyAction="*")]
        ProcScribe.StruktMain.selectTaskByParentWorkflowIDResponse selectTaskByParentWorkflowID(ProcScribe.StruktMain.selectTaskByParentWorkflowIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/selectTaskByParentWorkflowID", ReplyAction="*")]
        System.Threading.Tasks.Task<ProcScribe.StruktMain.selectTaskByParentWorkflowIDResponse> selectTaskByParentWorkflowIDAsync(ProcScribe.StruktMain.selectTaskByParentWorkflowIDRequest request);
        
        // CODEGEN: Generating message contract since element name strUserID from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/selectTaskByUserID", ReplyAction="*")]
        ProcScribe.StruktMain.selectTaskByUserIDResponse selectTaskByUserID(ProcScribe.StruktMain.selectTaskByUserIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/selectTaskByUserID", ReplyAction="*")]
        System.Threading.Tasks.Task<ProcScribe.StruktMain.selectTaskByUserIDResponse> selectTaskByUserIDAsync(ProcScribe.StruktMain.selectTaskByUserIDRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class selectWorkflowRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="selectWorkflow", Namespace="http://tempuri.org/", Order=0)]
        public ProcScribe.StruktMain.selectWorkflowRequestBody Body;
        
        public selectWorkflowRequest() {
        }
        
        public selectWorkflowRequest(ProcScribe.StruktMain.selectWorkflowRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class selectWorkflowRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strWorkflowID;
        
        public selectWorkflowRequestBody() {
        }
        
        public selectWorkflowRequestBody(string strWorkflowID) {
            this.strWorkflowID = strWorkflowID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class selectWorkflowResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="selectWorkflowResponse", Namespace="http://tempuri.org/", Order=0)]
        public ProcScribe.StruktMain.selectWorkflowResponseBody Body;
        
        public selectWorkflowResponse() {
        }
        
        public selectWorkflowResponse(ProcScribe.StruktMain.selectWorkflowResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class selectWorkflowResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string selectWorkflowResult;
        
        public selectWorkflowResponseBody() {
        }
        
        public selectWorkflowResponseBody(string selectWorkflowResult) {
            this.selectWorkflowResult = selectWorkflowResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addWorkflowRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addWorkflow", Namespace="http://tempuri.org/", Order=0)]
        public ProcScribe.StruktMain.addWorkflowRequestBody Body;
        
        public addWorkflowRequest() {
        }
        
        public addWorkflowRequest(ProcScribe.StruktMain.addWorkflowRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class addWorkflowRequestBody {
        
        public addWorkflowRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addWorkflowResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addWorkflowResponse", Namespace="http://tempuri.org/", Order=0)]
        public ProcScribe.StruktMain.addWorkflowResponseBody Body;
        
        public addWorkflowResponse() {
        }
        
        public addWorkflowResponse(ProcScribe.StruktMain.addWorkflowResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class addWorkflowResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string addWorkflowResult;
        
        public addWorkflowResponseBody() {
        }
        
        public addWorkflowResponseBody(string addWorkflowResult) {
            this.addWorkflowResult = addWorkflowResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class editWorkflowRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="editWorkflow", Namespace="http://tempuri.org/", Order=0)]
        public ProcScribe.StruktMain.editWorkflowRequestBody Body;
        
        public editWorkflowRequest() {
        }
        
        public editWorkflowRequest(ProcScribe.StruktMain.editWorkflowRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class editWorkflowRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strWorkflow;
        
        public editWorkflowRequestBody() {
        }
        
        public editWorkflowRequestBody(string strWorkflow) {
            this.strWorkflow = strWorkflow;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class editWorkflowResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="editWorkflowResponse", Namespace="http://tempuri.org/", Order=0)]
        public ProcScribe.StruktMain.editWorkflowResponseBody Body;
        
        public editWorkflowResponse() {
        }
        
        public editWorkflowResponse(ProcScribe.StruktMain.editWorkflowResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class editWorkflowResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string editWorkflowResult;
        
        public editWorkflowResponseBody() {
        }
        
        public editWorkflowResponseBody(string editWorkflowResult) {
            this.editWorkflowResult = editWorkflowResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class deleteWorkflowRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="deleteWorkflow", Namespace="http://tempuri.org/", Order=0)]
        public ProcScribe.StruktMain.deleteWorkflowRequestBody Body;
        
        public deleteWorkflowRequest() {
        }
        
        public deleteWorkflowRequest(ProcScribe.StruktMain.deleteWorkflowRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class deleteWorkflowRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strWorkflowID;
        
        public deleteWorkflowRequestBody() {
        }
        
        public deleteWorkflowRequestBody(string strWorkflowID) {
            this.strWorkflowID = strWorkflowID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class deleteWorkflowResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="deleteWorkflowResponse", Namespace="http://tempuri.org/", Order=0)]
        public ProcScribe.StruktMain.deleteWorkflowResponseBody Body;
        
        public deleteWorkflowResponse() {
        }
        
        public deleteWorkflowResponse(ProcScribe.StruktMain.deleteWorkflowResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class deleteWorkflowResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string deleteWorkflowResult;
        
        public deleteWorkflowResponseBody() {
        }
        
        public deleteWorkflowResponseBody(string deleteWorkflowResult) {
            this.deleteWorkflowResult = deleteWorkflowResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class selectTaskRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="selectTask", Namespace="http://tempuri.org/", Order=0)]
        public ProcScribe.StruktMain.selectTaskRequestBody Body;
        
        public selectTaskRequest() {
        }
        
        public selectTaskRequest(ProcScribe.StruktMain.selectTaskRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class selectTaskRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strTaskID;
        
        public selectTaskRequestBody() {
        }
        
        public selectTaskRequestBody(string strTaskID) {
            this.strTaskID = strTaskID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class selectTaskResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="selectTaskResponse", Namespace="http://tempuri.org/", Order=0)]
        public ProcScribe.StruktMain.selectTaskResponseBody Body;
        
        public selectTaskResponse() {
        }
        
        public selectTaskResponse(ProcScribe.StruktMain.selectTaskResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class selectTaskResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string selectTaskResult;
        
        public selectTaskResponseBody() {
        }
        
        public selectTaskResponseBody(string selectTaskResult) {
            this.selectTaskResult = selectTaskResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addTaskRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addTask", Namespace="http://tempuri.org/", Order=0)]
        public ProcScribe.StruktMain.addTaskRequestBody Body;
        
        public addTaskRequest() {
        }
        
        public addTaskRequest(ProcScribe.StruktMain.addTaskRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class addTaskRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strTaskObject;
        
        public addTaskRequestBody() {
        }
        
        public addTaskRequestBody(string strTaskObject) {
            this.strTaskObject = strTaskObject;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addTaskResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addTaskResponse", Namespace="http://tempuri.org/", Order=0)]
        public ProcScribe.StruktMain.addTaskResponseBody Body;
        
        public addTaskResponse() {
        }
        
        public addTaskResponse(ProcScribe.StruktMain.addTaskResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class addTaskResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string addTaskResult;
        
        public addTaskResponseBody() {
        }
        
        public addTaskResponseBody(string addTaskResult) {
            this.addTaskResult = addTaskResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class editTaskRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="editTask", Namespace="http://tempuri.org/", Order=0)]
        public ProcScribe.StruktMain.editTaskRequestBody Body;
        
        public editTaskRequest() {
        }
        
        public editTaskRequest(ProcScribe.StruktMain.editTaskRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class editTaskRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strTask;
        
        public editTaskRequestBody() {
        }
        
        public editTaskRequestBody(string strTask) {
            this.strTask = strTask;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class editTaskResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="editTaskResponse", Namespace="http://tempuri.org/", Order=0)]
        public ProcScribe.StruktMain.editTaskResponseBody Body;
        
        public editTaskResponse() {
        }
        
        public editTaskResponse(ProcScribe.StruktMain.editTaskResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class editTaskResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string editTaskResult;
        
        public editTaskResponseBody() {
        }
        
        public editTaskResponseBody(string editTaskResult) {
            this.editTaskResult = editTaskResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class deleteTaskRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="deleteTask", Namespace="http://tempuri.org/", Order=0)]
        public ProcScribe.StruktMain.deleteTaskRequestBody Body;
        
        public deleteTaskRequest() {
        }
        
        public deleteTaskRequest(ProcScribe.StruktMain.deleteTaskRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class deleteTaskRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strTaskID;
        
        public deleteTaskRequestBody() {
        }
        
        public deleteTaskRequestBody(string strTaskID) {
            this.strTaskID = strTaskID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class deleteTaskResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="deleteTaskResponse", Namespace="http://tempuri.org/", Order=0)]
        public ProcScribe.StruktMain.deleteTaskResponseBody Body;
        
        public deleteTaskResponse() {
        }
        
        public deleteTaskResponse(ProcScribe.StruktMain.deleteTaskResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class deleteTaskResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string deleteTaskResult;
        
        public deleteTaskResponseBody() {
        }
        
        public deleteTaskResponseBody(string deleteTaskResult) {
            this.deleteTaskResult = deleteTaskResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class selectTaskProcessAllRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="selectTaskProcessAll", Namespace="http://tempuri.org/", Order=0)]
        public ProcScribe.StruktMain.selectTaskProcessAllRequestBody Body;
        
        public selectTaskProcessAllRequest() {
        }
        
        public selectTaskProcessAllRequest(ProcScribe.StruktMain.selectTaskProcessAllRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class selectTaskProcessAllRequestBody {
        
        public selectTaskProcessAllRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class selectTaskProcessAllResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="selectTaskProcessAllResponse", Namespace="http://tempuri.org/", Order=0)]
        public ProcScribe.StruktMain.selectTaskProcessAllResponseBody Body;
        
        public selectTaskProcessAllResponse() {
        }
        
        public selectTaskProcessAllResponse(ProcScribe.StruktMain.selectTaskProcessAllResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class selectTaskProcessAllResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string selectTaskProcessAllResult;
        
        public selectTaskProcessAllResponseBody() {
        }
        
        public selectTaskProcessAllResponseBody(string selectTaskProcessAllResult) {
            this.selectTaskProcessAllResult = selectTaskProcessAllResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class selectTaskByParentWorkflowIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="selectTaskByParentWorkflowID", Namespace="http://tempuri.org/", Order=0)]
        public ProcScribe.StruktMain.selectTaskByParentWorkflowIDRequestBody Body;
        
        public selectTaskByParentWorkflowIDRequest() {
        }
        
        public selectTaskByParentWorkflowIDRequest(ProcScribe.StruktMain.selectTaskByParentWorkflowIDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class selectTaskByParentWorkflowIDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strParentWorkflowID;
        
        public selectTaskByParentWorkflowIDRequestBody() {
        }
        
        public selectTaskByParentWorkflowIDRequestBody(string strParentWorkflowID) {
            this.strParentWorkflowID = strParentWorkflowID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class selectTaskByParentWorkflowIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="selectTaskByParentWorkflowIDResponse", Namespace="http://tempuri.org/", Order=0)]
        public ProcScribe.StruktMain.selectTaskByParentWorkflowIDResponseBody Body;
        
        public selectTaskByParentWorkflowIDResponse() {
        }
        
        public selectTaskByParentWorkflowIDResponse(ProcScribe.StruktMain.selectTaskByParentWorkflowIDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class selectTaskByParentWorkflowIDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string selectTaskByParentWorkflowIDResult;
        
        public selectTaskByParentWorkflowIDResponseBody() {
        }
        
        public selectTaskByParentWorkflowIDResponseBody(string selectTaskByParentWorkflowIDResult) {
            this.selectTaskByParentWorkflowIDResult = selectTaskByParentWorkflowIDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class selectTaskByUserIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="selectTaskByUserID", Namespace="http://tempuri.org/", Order=0)]
        public ProcScribe.StruktMain.selectTaskByUserIDRequestBody Body;
        
        public selectTaskByUserIDRequest() {
        }
        
        public selectTaskByUserIDRequest(ProcScribe.StruktMain.selectTaskByUserIDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class selectTaskByUserIDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strUserID;
        
        public selectTaskByUserIDRequestBody() {
        }
        
        public selectTaskByUserIDRequestBody(string strUserID) {
            this.strUserID = strUserID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class selectTaskByUserIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="selectTaskByUserIDResponse", Namespace="http://tempuri.org/", Order=0)]
        public ProcScribe.StruktMain.selectTaskByUserIDResponseBody Body;
        
        public selectTaskByUserIDResponse() {
        }
        
        public selectTaskByUserIDResponse(ProcScribe.StruktMain.selectTaskByUserIDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class selectTaskByUserIDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string selectTaskByUserIDResult;
        
        public selectTaskByUserIDResponseBody() {
        }
        
        public selectTaskByUserIDResponseBody(string selectTaskByUserIDResult) {
            this.selectTaskByUserIDResult = selectTaskByUserIDResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface StruktMainSoapChannel : ProcScribe.StruktMain.StruktMainSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StruktMainSoapClient : System.ServiceModel.ClientBase<ProcScribe.StruktMain.StruktMainSoap>, ProcScribe.StruktMain.StruktMainSoap {
        
        public StruktMainSoapClient() {
        }
        
        public StruktMainSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StruktMainSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StruktMainSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StruktMainSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProcScribe.StruktMain.selectWorkflowResponse ProcScribe.StruktMain.StruktMainSoap.selectWorkflow(ProcScribe.StruktMain.selectWorkflowRequest request) {
            return base.Channel.selectWorkflow(request);
        }
        
        public string selectWorkflow(string strWorkflowID) {
            ProcScribe.StruktMain.selectWorkflowRequest inValue = new ProcScribe.StruktMain.selectWorkflowRequest();
            inValue.Body = new ProcScribe.StruktMain.selectWorkflowRequestBody();
            inValue.Body.strWorkflowID = strWorkflowID;
            ProcScribe.StruktMain.selectWorkflowResponse retVal = ((ProcScribe.StruktMain.StruktMainSoap)(this)).selectWorkflow(inValue);
            return retVal.Body.selectWorkflowResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProcScribe.StruktMain.selectWorkflowResponse> ProcScribe.StruktMain.StruktMainSoap.selectWorkflowAsync(ProcScribe.StruktMain.selectWorkflowRequest request) {
            return base.Channel.selectWorkflowAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProcScribe.StruktMain.selectWorkflowResponse> selectWorkflowAsync(string strWorkflowID) {
            ProcScribe.StruktMain.selectWorkflowRequest inValue = new ProcScribe.StruktMain.selectWorkflowRequest();
            inValue.Body = new ProcScribe.StruktMain.selectWorkflowRequestBody();
            inValue.Body.strWorkflowID = strWorkflowID;
            return ((ProcScribe.StruktMain.StruktMainSoap)(this)).selectWorkflowAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProcScribe.StruktMain.addWorkflowResponse ProcScribe.StruktMain.StruktMainSoap.addWorkflow(ProcScribe.StruktMain.addWorkflowRequest request) {
            return base.Channel.addWorkflow(request);
        }
        
        public string addWorkflow() {
            ProcScribe.StruktMain.addWorkflowRequest inValue = new ProcScribe.StruktMain.addWorkflowRequest();
            inValue.Body = new ProcScribe.StruktMain.addWorkflowRequestBody();
            ProcScribe.StruktMain.addWorkflowResponse retVal = ((ProcScribe.StruktMain.StruktMainSoap)(this)).addWorkflow(inValue);
            return retVal.Body.addWorkflowResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProcScribe.StruktMain.addWorkflowResponse> ProcScribe.StruktMain.StruktMainSoap.addWorkflowAsync(ProcScribe.StruktMain.addWorkflowRequest request) {
            return base.Channel.addWorkflowAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProcScribe.StruktMain.addWorkflowResponse> addWorkflowAsync() {
            ProcScribe.StruktMain.addWorkflowRequest inValue = new ProcScribe.StruktMain.addWorkflowRequest();
            inValue.Body = new ProcScribe.StruktMain.addWorkflowRequestBody();
            return ((ProcScribe.StruktMain.StruktMainSoap)(this)).addWorkflowAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProcScribe.StruktMain.editWorkflowResponse ProcScribe.StruktMain.StruktMainSoap.editWorkflow(ProcScribe.StruktMain.editWorkflowRequest request) {
            return base.Channel.editWorkflow(request);
        }
        
        public string editWorkflow(string strWorkflow) {
            ProcScribe.StruktMain.editWorkflowRequest inValue = new ProcScribe.StruktMain.editWorkflowRequest();
            inValue.Body = new ProcScribe.StruktMain.editWorkflowRequestBody();
            inValue.Body.strWorkflow = strWorkflow;
            ProcScribe.StruktMain.editWorkflowResponse retVal = ((ProcScribe.StruktMain.StruktMainSoap)(this)).editWorkflow(inValue);
            return retVal.Body.editWorkflowResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProcScribe.StruktMain.editWorkflowResponse> ProcScribe.StruktMain.StruktMainSoap.editWorkflowAsync(ProcScribe.StruktMain.editWorkflowRequest request) {
            return base.Channel.editWorkflowAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProcScribe.StruktMain.editWorkflowResponse> editWorkflowAsync(string strWorkflow) {
            ProcScribe.StruktMain.editWorkflowRequest inValue = new ProcScribe.StruktMain.editWorkflowRequest();
            inValue.Body = new ProcScribe.StruktMain.editWorkflowRequestBody();
            inValue.Body.strWorkflow = strWorkflow;
            return ((ProcScribe.StruktMain.StruktMainSoap)(this)).editWorkflowAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProcScribe.StruktMain.deleteWorkflowResponse ProcScribe.StruktMain.StruktMainSoap.deleteWorkflow(ProcScribe.StruktMain.deleteWorkflowRequest request) {
            return base.Channel.deleteWorkflow(request);
        }
        
        public string deleteWorkflow(string strWorkflowID) {
            ProcScribe.StruktMain.deleteWorkflowRequest inValue = new ProcScribe.StruktMain.deleteWorkflowRequest();
            inValue.Body = new ProcScribe.StruktMain.deleteWorkflowRequestBody();
            inValue.Body.strWorkflowID = strWorkflowID;
            ProcScribe.StruktMain.deleteWorkflowResponse retVal = ((ProcScribe.StruktMain.StruktMainSoap)(this)).deleteWorkflow(inValue);
            return retVal.Body.deleteWorkflowResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProcScribe.StruktMain.deleteWorkflowResponse> ProcScribe.StruktMain.StruktMainSoap.deleteWorkflowAsync(ProcScribe.StruktMain.deleteWorkflowRequest request) {
            return base.Channel.deleteWorkflowAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProcScribe.StruktMain.deleteWorkflowResponse> deleteWorkflowAsync(string strWorkflowID) {
            ProcScribe.StruktMain.deleteWorkflowRequest inValue = new ProcScribe.StruktMain.deleteWorkflowRequest();
            inValue.Body = new ProcScribe.StruktMain.deleteWorkflowRequestBody();
            inValue.Body.strWorkflowID = strWorkflowID;
            return ((ProcScribe.StruktMain.StruktMainSoap)(this)).deleteWorkflowAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProcScribe.StruktMain.selectTaskResponse ProcScribe.StruktMain.StruktMainSoap.selectTask(ProcScribe.StruktMain.selectTaskRequest request) {
            return base.Channel.selectTask(request);
        }
        
        public string selectTask(string strTaskID) {
            ProcScribe.StruktMain.selectTaskRequest inValue = new ProcScribe.StruktMain.selectTaskRequest();
            inValue.Body = new ProcScribe.StruktMain.selectTaskRequestBody();
            inValue.Body.strTaskID = strTaskID;
            ProcScribe.StruktMain.selectTaskResponse retVal = ((ProcScribe.StruktMain.StruktMainSoap)(this)).selectTask(inValue);
            return retVal.Body.selectTaskResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProcScribe.StruktMain.selectTaskResponse> ProcScribe.StruktMain.StruktMainSoap.selectTaskAsync(ProcScribe.StruktMain.selectTaskRequest request) {
            return base.Channel.selectTaskAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProcScribe.StruktMain.selectTaskResponse> selectTaskAsync(string strTaskID) {
            ProcScribe.StruktMain.selectTaskRequest inValue = new ProcScribe.StruktMain.selectTaskRequest();
            inValue.Body = new ProcScribe.StruktMain.selectTaskRequestBody();
            inValue.Body.strTaskID = strTaskID;
            return ((ProcScribe.StruktMain.StruktMainSoap)(this)).selectTaskAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProcScribe.StruktMain.addTaskResponse ProcScribe.StruktMain.StruktMainSoap.addTask(ProcScribe.StruktMain.addTaskRequest request) {
            return base.Channel.addTask(request);
        }
        
        public string addTask(string strTaskObject) {
            ProcScribe.StruktMain.addTaskRequest inValue = new ProcScribe.StruktMain.addTaskRequest();
            inValue.Body = new ProcScribe.StruktMain.addTaskRequestBody();
            inValue.Body.strTaskObject = strTaskObject;
            ProcScribe.StruktMain.addTaskResponse retVal = ((ProcScribe.StruktMain.StruktMainSoap)(this)).addTask(inValue);
            return retVal.Body.addTaskResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProcScribe.StruktMain.addTaskResponse> ProcScribe.StruktMain.StruktMainSoap.addTaskAsync(ProcScribe.StruktMain.addTaskRequest request) {
            return base.Channel.addTaskAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProcScribe.StruktMain.addTaskResponse> addTaskAsync(string strTaskObject) {
            ProcScribe.StruktMain.addTaskRequest inValue = new ProcScribe.StruktMain.addTaskRequest();
            inValue.Body = new ProcScribe.StruktMain.addTaskRequestBody();
            inValue.Body.strTaskObject = strTaskObject;
            return ((ProcScribe.StruktMain.StruktMainSoap)(this)).addTaskAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProcScribe.StruktMain.editTaskResponse ProcScribe.StruktMain.StruktMainSoap.editTask(ProcScribe.StruktMain.editTaskRequest request) {
            return base.Channel.editTask(request);
        }
        
        public string editTask(string strTask) {
            ProcScribe.StruktMain.editTaskRequest inValue = new ProcScribe.StruktMain.editTaskRequest();
            inValue.Body = new ProcScribe.StruktMain.editTaskRequestBody();
            inValue.Body.strTask = strTask;
            ProcScribe.StruktMain.editTaskResponse retVal = ((ProcScribe.StruktMain.StruktMainSoap)(this)).editTask(inValue);
            return retVal.Body.editTaskResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProcScribe.StruktMain.editTaskResponse> ProcScribe.StruktMain.StruktMainSoap.editTaskAsync(ProcScribe.StruktMain.editTaskRequest request) {
            return base.Channel.editTaskAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProcScribe.StruktMain.editTaskResponse> editTaskAsync(string strTask) {
            ProcScribe.StruktMain.editTaskRequest inValue = new ProcScribe.StruktMain.editTaskRequest();
            inValue.Body = new ProcScribe.StruktMain.editTaskRequestBody();
            inValue.Body.strTask = strTask;
            return ((ProcScribe.StruktMain.StruktMainSoap)(this)).editTaskAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProcScribe.StruktMain.deleteTaskResponse ProcScribe.StruktMain.StruktMainSoap.deleteTask(ProcScribe.StruktMain.deleteTaskRequest request) {
            return base.Channel.deleteTask(request);
        }
        
        public string deleteTask(string strTaskID) {
            ProcScribe.StruktMain.deleteTaskRequest inValue = new ProcScribe.StruktMain.deleteTaskRequest();
            inValue.Body = new ProcScribe.StruktMain.deleteTaskRequestBody();
            inValue.Body.strTaskID = strTaskID;
            ProcScribe.StruktMain.deleteTaskResponse retVal = ((ProcScribe.StruktMain.StruktMainSoap)(this)).deleteTask(inValue);
            return retVal.Body.deleteTaskResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProcScribe.StruktMain.deleteTaskResponse> ProcScribe.StruktMain.StruktMainSoap.deleteTaskAsync(ProcScribe.StruktMain.deleteTaskRequest request) {
            return base.Channel.deleteTaskAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProcScribe.StruktMain.deleteTaskResponse> deleteTaskAsync(string strTaskID) {
            ProcScribe.StruktMain.deleteTaskRequest inValue = new ProcScribe.StruktMain.deleteTaskRequest();
            inValue.Body = new ProcScribe.StruktMain.deleteTaskRequestBody();
            inValue.Body.strTaskID = strTaskID;
            return ((ProcScribe.StruktMain.StruktMainSoap)(this)).deleteTaskAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProcScribe.StruktMain.selectTaskProcessAllResponse ProcScribe.StruktMain.StruktMainSoap.selectTaskProcessAll(ProcScribe.StruktMain.selectTaskProcessAllRequest request) {
            return base.Channel.selectTaskProcessAll(request);
        }
        
        public string selectTaskProcessAll() {
            ProcScribe.StruktMain.selectTaskProcessAllRequest inValue = new ProcScribe.StruktMain.selectTaskProcessAllRequest();
            inValue.Body = new ProcScribe.StruktMain.selectTaskProcessAllRequestBody();
            ProcScribe.StruktMain.selectTaskProcessAllResponse retVal = ((ProcScribe.StruktMain.StruktMainSoap)(this)).selectTaskProcessAll(inValue);
            return retVal.Body.selectTaskProcessAllResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProcScribe.StruktMain.selectTaskProcessAllResponse> ProcScribe.StruktMain.StruktMainSoap.selectTaskProcessAllAsync(ProcScribe.StruktMain.selectTaskProcessAllRequest request) {
            return base.Channel.selectTaskProcessAllAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProcScribe.StruktMain.selectTaskProcessAllResponse> selectTaskProcessAllAsync() {
            ProcScribe.StruktMain.selectTaskProcessAllRequest inValue = new ProcScribe.StruktMain.selectTaskProcessAllRequest();
            inValue.Body = new ProcScribe.StruktMain.selectTaskProcessAllRequestBody();
            return ((ProcScribe.StruktMain.StruktMainSoap)(this)).selectTaskProcessAllAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProcScribe.StruktMain.selectTaskByParentWorkflowIDResponse ProcScribe.StruktMain.StruktMainSoap.selectTaskByParentWorkflowID(ProcScribe.StruktMain.selectTaskByParentWorkflowIDRequest request) {
            return base.Channel.selectTaskByParentWorkflowID(request);
        }
        
        public string selectTaskByParentWorkflowID(string strParentWorkflowID) {
            ProcScribe.StruktMain.selectTaskByParentWorkflowIDRequest inValue = new ProcScribe.StruktMain.selectTaskByParentWorkflowIDRequest();
            inValue.Body = new ProcScribe.StruktMain.selectTaskByParentWorkflowIDRequestBody();
            inValue.Body.strParentWorkflowID = strParentWorkflowID;
            ProcScribe.StruktMain.selectTaskByParentWorkflowIDResponse retVal = ((ProcScribe.StruktMain.StruktMainSoap)(this)).selectTaskByParentWorkflowID(inValue);
            return retVal.Body.selectTaskByParentWorkflowIDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProcScribe.StruktMain.selectTaskByParentWorkflowIDResponse> ProcScribe.StruktMain.StruktMainSoap.selectTaskByParentWorkflowIDAsync(ProcScribe.StruktMain.selectTaskByParentWorkflowIDRequest request) {
            return base.Channel.selectTaskByParentWorkflowIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProcScribe.StruktMain.selectTaskByParentWorkflowIDResponse> selectTaskByParentWorkflowIDAsync(string strParentWorkflowID) {
            ProcScribe.StruktMain.selectTaskByParentWorkflowIDRequest inValue = new ProcScribe.StruktMain.selectTaskByParentWorkflowIDRequest();
            inValue.Body = new ProcScribe.StruktMain.selectTaskByParentWorkflowIDRequestBody();
            inValue.Body.strParentWorkflowID = strParentWorkflowID;
            return ((ProcScribe.StruktMain.StruktMainSoap)(this)).selectTaskByParentWorkflowIDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProcScribe.StruktMain.selectTaskByUserIDResponse ProcScribe.StruktMain.StruktMainSoap.selectTaskByUserID(ProcScribe.StruktMain.selectTaskByUserIDRequest request) {
            return base.Channel.selectTaskByUserID(request);
        }
        
        public string selectTaskByUserID(string strUserID) {
            ProcScribe.StruktMain.selectTaskByUserIDRequest inValue = new ProcScribe.StruktMain.selectTaskByUserIDRequest();
            inValue.Body = new ProcScribe.StruktMain.selectTaskByUserIDRequestBody();
            inValue.Body.strUserID = strUserID;
            ProcScribe.StruktMain.selectTaskByUserIDResponse retVal = ((ProcScribe.StruktMain.StruktMainSoap)(this)).selectTaskByUserID(inValue);
            return retVal.Body.selectTaskByUserIDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProcScribe.StruktMain.selectTaskByUserIDResponse> ProcScribe.StruktMain.StruktMainSoap.selectTaskByUserIDAsync(ProcScribe.StruktMain.selectTaskByUserIDRequest request) {
            return base.Channel.selectTaskByUserIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProcScribe.StruktMain.selectTaskByUserIDResponse> selectTaskByUserIDAsync(string strUserID) {
            ProcScribe.StruktMain.selectTaskByUserIDRequest inValue = new ProcScribe.StruktMain.selectTaskByUserIDRequest();
            inValue.Body = new ProcScribe.StruktMain.selectTaskByUserIDRequestBody();
            inValue.Body.strUserID = strUserID;
            return ((ProcScribe.StruktMain.StruktMainSoap)(this)).selectTaskByUserIDAsync(inValue);
        }
    }
}
