//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcScribe.StruktMain {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="StruktMain.StruktMainSoap")]
    public interface StruktMainSoap {
        
        // CODEGEN: Generating message contract since element name addWorkflowResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/addWorkflow", ReplyAction="*")]
        ProcScribe.StruktMain.addWorkflowResponse addWorkflow(ProcScribe.StruktMain.addWorkflowRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/addWorkflow", ReplyAction="*")]
        System.Threading.Tasks.Task<ProcScribe.StruktMain.addWorkflowResponse> addWorkflowAsync(ProcScribe.StruktMain.addWorkflowRequest request);
        
        // CODEGEN: Generating message contract since element name strWorkflow from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/editWorkflow", ReplyAction="*")]
        ProcScribe.StruktMain.editWorkflowResponse editWorkflow(ProcScribe.StruktMain.editWorkflowRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/editWorkflow", ReplyAction="*")]
        System.Threading.Tasks.Task<ProcScribe.StruktMain.editWorkflowResponse> editWorkflowAsync(ProcScribe.StruktMain.editWorkflowRequest request);
        
        // CODEGEN: Generating message contract since element name strWorkflowID from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/deleteWorkflow", ReplyAction="*")]
        ProcScribe.StruktMain.deleteWorkflowResponse deleteWorkflow(ProcScribe.StruktMain.deleteWorkflowRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/deleteWorkflow", ReplyAction="*")]
        System.Threading.Tasks.Task<ProcScribe.StruktMain.deleteWorkflowResponse> deleteWorkflowAsync(ProcScribe.StruktMain.deleteWorkflowRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addWorkflowRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addWorkflow", Namespace="http://tempuri.org/", Order=0)]
        public ProcScribe.StruktMain.addWorkflowRequestBody Body;
        
        public addWorkflowRequest() {
        }
        
        public addWorkflowRequest(ProcScribe.StruktMain.addWorkflowRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class addWorkflowRequestBody {
        
        public addWorkflowRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addWorkflowResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addWorkflowResponse", Namespace="http://tempuri.org/", Order=0)]
        public ProcScribe.StruktMain.addWorkflowResponseBody Body;
        
        public addWorkflowResponse() {
        }
        
        public addWorkflowResponse(ProcScribe.StruktMain.addWorkflowResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class addWorkflowResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string addWorkflowResult;
        
        public addWorkflowResponseBody() {
        }
        
        public addWorkflowResponseBody(string addWorkflowResult) {
            this.addWorkflowResult = addWorkflowResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class editWorkflowRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="editWorkflow", Namespace="http://tempuri.org/", Order=0)]
        public ProcScribe.StruktMain.editWorkflowRequestBody Body;
        
        public editWorkflowRequest() {
        }
        
        public editWorkflowRequest(ProcScribe.StruktMain.editWorkflowRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class editWorkflowRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strWorkflow;
        
        public editWorkflowRequestBody() {
        }
        
        public editWorkflowRequestBody(string strWorkflow) {
            this.strWorkflow = strWorkflow;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class editWorkflowResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="editWorkflowResponse", Namespace="http://tempuri.org/", Order=0)]
        public ProcScribe.StruktMain.editWorkflowResponseBody Body;
        
        public editWorkflowResponse() {
        }
        
        public editWorkflowResponse(ProcScribe.StruktMain.editWorkflowResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class editWorkflowResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string editWorkflowResult;
        
        public editWorkflowResponseBody() {
        }
        
        public editWorkflowResponseBody(string editWorkflowResult) {
            this.editWorkflowResult = editWorkflowResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class deleteWorkflowRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="deleteWorkflow", Namespace="http://tempuri.org/", Order=0)]
        public ProcScribe.StruktMain.deleteWorkflowRequestBody Body;
        
        public deleteWorkflowRequest() {
        }
        
        public deleteWorkflowRequest(ProcScribe.StruktMain.deleteWorkflowRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class deleteWorkflowRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strWorkflowID;
        
        public deleteWorkflowRequestBody() {
        }
        
        public deleteWorkflowRequestBody(string strWorkflowID) {
            this.strWorkflowID = strWorkflowID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class deleteWorkflowResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="deleteWorkflowResponse", Namespace="http://tempuri.org/", Order=0)]
        public ProcScribe.StruktMain.deleteWorkflowResponseBody Body;
        
        public deleteWorkflowResponse() {
        }
        
        public deleteWorkflowResponse(ProcScribe.StruktMain.deleteWorkflowResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class deleteWorkflowResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string deleteWorkflowResult;
        
        public deleteWorkflowResponseBody() {
        }
        
        public deleteWorkflowResponseBody(string deleteWorkflowResult) {
            this.deleteWorkflowResult = deleteWorkflowResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface StruktMainSoapChannel : ProcScribe.StruktMain.StruktMainSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StruktMainSoapClient : System.ServiceModel.ClientBase<ProcScribe.StruktMain.StruktMainSoap>, ProcScribe.StruktMain.StruktMainSoap {
        
        public StruktMainSoapClient() {
        }
        
        public StruktMainSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StruktMainSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StruktMainSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StruktMainSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProcScribe.StruktMain.addWorkflowResponse ProcScribe.StruktMain.StruktMainSoap.addWorkflow(ProcScribe.StruktMain.addWorkflowRequest request) {
            return base.Channel.addWorkflow(request);
        }
        
        public string addWorkflow() {
            ProcScribe.StruktMain.addWorkflowRequest inValue = new ProcScribe.StruktMain.addWorkflowRequest();
            inValue.Body = new ProcScribe.StruktMain.addWorkflowRequestBody();
            ProcScribe.StruktMain.addWorkflowResponse retVal = ((ProcScribe.StruktMain.StruktMainSoap)(this)).addWorkflow(inValue);
            return retVal.Body.addWorkflowResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProcScribe.StruktMain.addWorkflowResponse> ProcScribe.StruktMain.StruktMainSoap.addWorkflowAsync(ProcScribe.StruktMain.addWorkflowRequest request) {
            return base.Channel.addWorkflowAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProcScribe.StruktMain.addWorkflowResponse> addWorkflowAsync() {
            ProcScribe.StruktMain.addWorkflowRequest inValue = new ProcScribe.StruktMain.addWorkflowRequest();
            inValue.Body = new ProcScribe.StruktMain.addWorkflowRequestBody();
            return ((ProcScribe.StruktMain.StruktMainSoap)(this)).addWorkflowAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProcScribe.StruktMain.editWorkflowResponse ProcScribe.StruktMain.StruktMainSoap.editWorkflow(ProcScribe.StruktMain.editWorkflowRequest request) {
            return base.Channel.editWorkflow(request);
        }
        
        public string editWorkflow(string strWorkflow) {
            ProcScribe.StruktMain.editWorkflowRequest inValue = new ProcScribe.StruktMain.editWorkflowRequest();
            inValue.Body = new ProcScribe.StruktMain.editWorkflowRequestBody();
            inValue.Body.strWorkflow = strWorkflow;
            ProcScribe.StruktMain.editWorkflowResponse retVal = ((ProcScribe.StruktMain.StruktMainSoap)(this)).editWorkflow(inValue);
            return retVal.Body.editWorkflowResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProcScribe.StruktMain.editWorkflowResponse> ProcScribe.StruktMain.StruktMainSoap.editWorkflowAsync(ProcScribe.StruktMain.editWorkflowRequest request) {
            return base.Channel.editWorkflowAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProcScribe.StruktMain.editWorkflowResponse> editWorkflowAsync(string strWorkflow) {
            ProcScribe.StruktMain.editWorkflowRequest inValue = new ProcScribe.StruktMain.editWorkflowRequest();
            inValue.Body = new ProcScribe.StruktMain.editWorkflowRequestBody();
            inValue.Body.strWorkflow = strWorkflow;
            return ((ProcScribe.StruktMain.StruktMainSoap)(this)).editWorkflowAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProcScribe.StruktMain.deleteWorkflowResponse ProcScribe.StruktMain.StruktMainSoap.deleteWorkflow(ProcScribe.StruktMain.deleteWorkflowRequest request) {
            return base.Channel.deleteWorkflow(request);
        }
        
        public string deleteWorkflow(string strWorkflowID) {
            ProcScribe.StruktMain.deleteWorkflowRequest inValue = new ProcScribe.StruktMain.deleteWorkflowRequest();
            inValue.Body = new ProcScribe.StruktMain.deleteWorkflowRequestBody();
            inValue.Body.strWorkflowID = strWorkflowID;
            ProcScribe.StruktMain.deleteWorkflowResponse retVal = ((ProcScribe.StruktMain.StruktMainSoap)(this)).deleteWorkflow(inValue);
            return retVal.Body.deleteWorkflowResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProcScribe.StruktMain.deleteWorkflowResponse> ProcScribe.StruktMain.StruktMainSoap.deleteWorkflowAsync(ProcScribe.StruktMain.deleteWorkflowRequest request) {
            return base.Channel.deleteWorkflowAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProcScribe.StruktMain.deleteWorkflowResponse> deleteWorkflowAsync(string strWorkflowID) {
            ProcScribe.StruktMain.deleteWorkflowRequest inValue = new ProcScribe.StruktMain.deleteWorkflowRequest();
            inValue.Body = new ProcScribe.StruktMain.deleteWorkflowRequestBody();
            inValue.Body.strWorkflowID = strWorkflowID;
            return ((ProcScribe.StruktMain.StruktMainSoap)(this)).deleteWorkflowAsync(inValue);
        }
    }
}
