//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mockup2.StruktWebservice {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="StruktWebservice.StruktUserSoap")]
    public interface StruktUserSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<string> HelloWorldAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/checkLogin", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable checkLogin(string strName, string strPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/checkLogin", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> checkLoginAsync(string strName, string strPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getProcessByUserID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable getProcessByUserID(string strID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getProcessByUserID", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> getProcessByUserIDAsync(string strID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getProcessAll", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable getProcessAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getProcessAll", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> getProcessAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getUserAll", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable getUserAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getUserAll", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> getUserAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getUserByStruktID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable getUserByStruktID(string strID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getUserByStruktID", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> getUserByStruktIDAsync(string strID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoadDescriptionDetail", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable LoadDescriptionDetail(string strID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoadDescriptionDetail", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> LoadDescriptionDetailAsync(string strID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddUptadeTaskDescription", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void AddUptadeTaskDescription(string strID, string Desc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddUptadeTaskDescription", ReplyAction="*")]
        System.Threading.Tasks.Task AddUptadeTaskDescriptionAsync(string strID, string Desc);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface StruktUserSoapChannel : Mockup2.StruktWebservice.StruktUserSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StruktUserSoapClient : System.ServiceModel.ClientBase<Mockup2.StruktWebservice.StruktUserSoap>, Mockup2.StruktWebservice.StruktUserSoap {
        
        public StruktUserSoapClient() {
        }
        
        public StruktUserSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StruktUserSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StruktUserSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StruktUserSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public System.Threading.Tasks.Task<string> HelloWorldAsync() {
            return base.Channel.HelloWorldAsync();
        }
        
        public System.Data.DataTable checkLogin(string strName, string strPassword) {
            return base.Channel.checkLogin(strName, strPassword);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> checkLoginAsync(string strName, string strPassword) {
            return base.Channel.checkLoginAsync(strName, strPassword);
        }
        
        public System.Data.DataTable getProcessByUserID(string strID) {
            return base.Channel.getProcessByUserID(strID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> getProcessByUserIDAsync(string strID) {
            return base.Channel.getProcessByUserIDAsync(strID);
        }
        
        public System.Data.DataTable getProcessAll() {
            return base.Channel.getProcessAll();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> getProcessAllAsync() {
            return base.Channel.getProcessAllAsync();
        }
        
        public System.Data.DataTable getUserAll() {
            return base.Channel.getUserAll();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> getUserAllAsync() {
            return base.Channel.getUserAllAsync();
        }
        
        public System.Data.DataTable getUserByStruktID(string strID) {
            return base.Channel.getUserByStruktID(strID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> getUserByStruktIDAsync(string strID) {
            return base.Channel.getUserByStruktIDAsync(strID);
        }
        
        public System.Data.DataTable LoadDescriptionDetail(string strID) {
            return base.Channel.LoadDescriptionDetail(strID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> LoadDescriptionDetailAsync(string strID) {
            return base.Channel.LoadDescriptionDetailAsync(strID);
        }
        
        public void AddUptadeTaskDescription(string strID, string Desc) {
            base.Channel.AddUptadeTaskDescription(strID, Desc);
        }
        
        public System.Threading.Tasks.Task AddUptadeTaskDescriptionAsync(string strID, string Desc) {
            return base.Channel.AddUptadeTaskDescriptionAsync(strID, Desc);
        }
    }
}
