//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcScribeOutlook.StruktMain {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="StruktMain.StruktMainSoap")]
    public interface StruktMainSoap {
        
        // CODEGEN: Generating message contract since element name strWorkflowID from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/selectWorkflow", ReplyAction="*")]
        ProcScribeOutlook.StruktMain.selectWorkflowResponse selectWorkflow(ProcScribeOutlook.StruktMain.selectWorkflowRequest request);
        
        // CODEGEN: Generating message contract since element name strProcessName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/addStruktProcess", ReplyAction="*")]
        ProcScribeOutlook.StruktMain.addStruktProcessResponse addStruktProcess(ProcScribeOutlook.StruktMain.addStruktProcessRequest request);
        
        // CODEGEN: Generating message contract since element name strStruktProcessName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/editStruktProcessName", ReplyAction="*")]
        ProcScribeOutlook.StruktMain.editStruktProcessNameResponse editStruktProcessName(ProcScribeOutlook.StruktMain.editStruktProcessNameRequest request);
        
        // CODEGEN: Generating message contract since element name deleteStruktProcessResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/deleteStruktProcess", ReplyAction="*")]
        ProcScribeOutlook.StruktMain.deleteStruktProcessResponse deleteStruktProcess(ProcScribeOutlook.StruktMain.deleteStruktProcessRequest request);
        
        // CODEGEN: Generating message contract since element name addWorkflowResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/addWorkflow", ReplyAction="*")]
        ProcScribeOutlook.StruktMain.addWorkflowResponse addWorkflow(ProcScribeOutlook.StruktMain.addWorkflowRequest request);
        
        // CODEGEN: Generating message contract since element name strWorkflow from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/editWorkflow", ReplyAction="*")]
        ProcScribeOutlook.StruktMain.editWorkflowResponse editWorkflow(ProcScribeOutlook.StruktMain.editWorkflowRequest request);
        
        // CODEGEN: Generating message contract since element name strWorkflowID from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/deleteWorkflow", ReplyAction="*")]
        ProcScribeOutlook.StruktMain.deleteWorkflowResponse deleteWorkflow(ProcScribeOutlook.StruktMain.deleteWorkflowRequest request);
        
        // CODEGEN: Generating message contract since element name strTaskID from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/selectTask", ReplyAction="*")]
        ProcScribeOutlook.StruktMain.selectTaskResponse selectTask(ProcScribeOutlook.StruktMain.selectTaskRequest request);
        
        // CODEGEN: Generating message contract since element name strTaskObject from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/addTask", ReplyAction="*")]
        ProcScribeOutlook.StruktMain.addTaskResponse addTask(ProcScribeOutlook.StruktMain.addTaskRequest request);
        
        // CODEGEN: Generating message contract since element name strTask from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/editTask", ReplyAction="*")]
        ProcScribeOutlook.StruktMain.editTaskResponse editTask(ProcScribeOutlook.StruktMain.editTaskRequest request);
        
        // CODEGEN: Generating message contract since element name strTaskID from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/deleteTask", ReplyAction="*")]
        ProcScribeOutlook.StruktMain.deleteTaskResponse deleteTask(ProcScribeOutlook.StruktMain.deleteTaskRequest request);
        
        // CODEGEN: Generating message contract since element name selectTaskProcessAllResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/selectTaskProcessAll", ReplyAction="*")]
        ProcScribeOutlook.StruktMain.selectTaskProcessAllResponse selectTaskProcessAll(ProcScribeOutlook.StruktMain.selectTaskProcessAllRequest request);
        
        // CODEGEN: Generating message contract since element name strParentWorkflowID from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/selectTaskByParentWorkflowID", ReplyAction="*")]
        ProcScribeOutlook.StruktMain.selectTaskByParentWorkflowIDResponse selectTaskByParentWorkflowID(ProcScribeOutlook.StruktMain.selectTaskByParentWorkflowIDRequest request);
        
        // CODEGEN: Generating message contract since element name strUserID from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/selectTaskByUserID", ReplyAction="*")]
        ProcScribeOutlook.StruktMain.selectTaskByUserIDResponse selectTaskByUserID(ProcScribeOutlook.StruktMain.selectTaskByUserIDRequest request);
        
        // CODEGEN: Generating message contract since element name getFileListResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getFileList", ReplyAction="*")]
        ProcScribeOutlook.StruktMain.getFileListResponse getFileList(ProcScribeOutlook.StruktMain.getFileListRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class selectWorkflowRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="selectWorkflow", Namespace="http://tempuri.org/", Order=0)]
        public ProcScribeOutlook.StruktMain.selectWorkflowRequestBody Body;
        
        public selectWorkflowRequest() {
        }
        
        public selectWorkflowRequest(ProcScribeOutlook.StruktMain.selectWorkflowRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class selectWorkflowRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strWorkflowID;
        
        public selectWorkflowRequestBody() {
        }
        
        public selectWorkflowRequestBody(string strWorkflowID) {
            this.strWorkflowID = strWorkflowID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class selectWorkflowResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="selectWorkflowResponse", Namespace="http://tempuri.org/", Order=0)]
        public ProcScribeOutlook.StruktMain.selectWorkflowResponseBody Body;
        
        public selectWorkflowResponse() {
        }
        
        public selectWorkflowResponse(ProcScribeOutlook.StruktMain.selectWorkflowResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class selectWorkflowResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string selectWorkflowResult;
        
        public selectWorkflowResponseBody() {
        }
        
        public selectWorkflowResponseBody(string selectWorkflowResult) {
            this.selectWorkflowResult = selectWorkflowResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addStruktProcessRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addStruktProcess", Namespace="http://tempuri.org/", Order=0)]
        public ProcScribeOutlook.StruktMain.addStruktProcessRequestBody Body;
        
        public addStruktProcessRequest() {
        }
        
        public addStruktProcessRequest(ProcScribeOutlook.StruktMain.addStruktProcessRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class addStruktProcessRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strProcessName;
        
        public addStruktProcessRequestBody() {
        }
        
        public addStruktProcessRequestBody(string strProcessName) {
            this.strProcessName = strProcessName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addStruktProcessResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addStruktProcessResponse", Namespace="http://tempuri.org/", Order=0)]
        public ProcScribeOutlook.StruktMain.addStruktProcessResponseBody Body;
        
        public addStruktProcessResponse() {
        }
        
        public addStruktProcessResponse(ProcScribeOutlook.StruktMain.addStruktProcessResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class addStruktProcessResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string addStruktProcessResult;
        
        public addStruktProcessResponseBody() {
        }
        
        public addStruktProcessResponseBody(string addStruktProcessResult) {
            this.addStruktProcessResult = addStruktProcessResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class editStruktProcessNameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="editStruktProcessName", Namespace="http://tempuri.org/", Order=0)]
        public ProcScribeOutlook.StruktMain.editStruktProcessNameRequestBody Body;
        
        public editStruktProcessNameRequest() {
        }
        
        public editStruktProcessNameRequest(ProcScribeOutlook.StruktMain.editStruktProcessNameRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class editStruktProcessNameRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int strStruktProcessID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string strStruktProcessName;
        
        public editStruktProcessNameRequestBody() {
        }
        
        public editStruktProcessNameRequestBody(int strStruktProcessID, string strStruktProcessName) {
            this.strStruktProcessID = strStruktProcessID;
            this.strStruktProcessName = strStruktProcessName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class editStruktProcessNameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="editStruktProcessNameResponse", Namespace="http://tempuri.org/", Order=0)]
        public ProcScribeOutlook.StruktMain.editStruktProcessNameResponseBody Body;
        
        public editStruktProcessNameResponse() {
        }
        
        public editStruktProcessNameResponse(ProcScribeOutlook.StruktMain.editStruktProcessNameResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class editStruktProcessNameResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string editStruktProcessNameResult;
        
        public editStruktProcessNameResponseBody() {
        }
        
        public editStruktProcessNameResponseBody(string editStruktProcessNameResult) {
            this.editStruktProcessNameResult = editStruktProcessNameResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class deleteStruktProcessRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="deleteStruktProcess", Namespace="http://tempuri.org/", Order=0)]
        public ProcScribeOutlook.StruktMain.deleteStruktProcessRequestBody Body;
        
        public deleteStruktProcessRequest() {
        }
        
        public deleteStruktProcessRequest(ProcScribeOutlook.StruktMain.deleteStruktProcessRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class deleteStruktProcessRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int intStruktProcessID;
        
        public deleteStruktProcessRequestBody() {
        }
        
        public deleteStruktProcessRequestBody(int intStruktProcessID) {
            this.intStruktProcessID = intStruktProcessID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class deleteStruktProcessResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="deleteStruktProcessResponse", Namespace="http://tempuri.org/", Order=0)]
        public ProcScribeOutlook.StruktMain.deleteStruktProcessResponseBody Body;
        
        public deleteStruktProcessResponse() {
        }
        
        public deleteStruktProcessResponse(ProcScribeOutlook.StruktMain.deleteStruktProcessResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class deleteStruktProcessResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string deleteStruktProcessResult;
        
        public deleteStruktProcessResponseBody() {
        }
        
        public deleteStruktProcessResponseBody(string deleteStruktProcessResult) {
            this.deleteStruktProcessResult = deleteStruktProcessResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addWorkflowRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addWorkflow", Namespace="http://tempuri.org/", Order=0)]
        public ProcScribeOutlook.StruktMain.addWorkflowRequestBody Body;
        
        public addWorkflowRequest() {
        }
        
        public addWorkflowRequest(ProcScribeOutlook.StruktMain.addWorkflowRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class addWorkflowRequestBody {
        
        public addWorkflowRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addWorkflowResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addWorkflowResponse", Namespace="http://tempuri.org/", Order=0)]
        public ProcScribeOutlook.StruktMain.addWorkflowResponseBody Body;
        
        public addWorkflowResponse() {
        }
        
        public addWorkflowResponse(ProcScribeOutlook.StruktMain.addWorkflowResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class addWorkflowResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string addWorkflowResult;
        
        public addWorkflowResponseBody() {
        }
        
        public addWorkflowResponseBody(string addWorkflowResult) {
            this.addWorkflowResult = addWorkflowResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class editWorkflowRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="editWorkflow", Namespace="http://tempuri.org/", Order=0)]
        public ProcScribeOutlook.StruktMain.editWorkflowRequestBody Body;
        
        public editWorkflowRequest() {
        }
        
        public editWorkflowRequest(ProcScribeOutlook.StruktMain.editWorkflowRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class editWorkflowRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strWorkflow;
        
        public editWorkflowRequestBody() {
        }
        
        public editWorkflowRequestBody(string strWorkflow) {
            this.strWorkflow = strWorkflow;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class editWorkflowResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="editWorkflowResponse", Namespace="http://tempuri.org/", Order=0)]
        public ProcScribeOutlook.StruktMain.editWorkflowResponseBody Body;
        
        public editWorkflowResponse() {
        }
        
        public editWorkflowResponse(ProcScribeOutlook.StruktMain.editWorkflowResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class editWorkflowResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string editWorkflowResult;
        
        public editWorkflowResponseBody() {
        }
        
        public editWorkflowResponseBody(string editWorkflowResult) {
            this.editWorkflowResult = editWorkflowResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class deleteWorkflowRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="deleteWorkflow", Namespace="http://tempuri.org/", Order=0)]
        public ProcScribeOutlook.StruktMain.deleteWorkflowRequestBody Body;
        
        public deleteWorkflowRequest() {
        }
        
        public deleteWorkflowRequest(ProcScribeOutlook.StruktMain.deleteWorkflowRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class deleteWorkflowRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strWorkflowID;
        
        public deleteWorkflowRequestBody() {
        }
        
        public deleteWorkflowRequestBody(string strWorkflowID) {
            this.strWorkflowID = strWorkflowID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class deleteWorkflowResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="deleteWorkflowResponse", Namespace="http://tempuri.org/", Order=0)]
        public ProcScribeOutlook.StruktMain.deleteWorkflowResponseBody Body;
        
        public deleteWorkflowResponse() {
        }
        
        public deleteWorkflowResponse(ProcScribeOutlook.StruktMain.deleteWorkflowResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class deleteWorkflowResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string deleteWorkflowResult;
        
        public deleteWorkflowResponseBody() {
        }
        
        public deleteWorkflowResponseBody(string deleteWorkflowResult) {
            this.deleteWorkflowResult = deleteWorkflowResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class selectTaskRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="selectTask", Namespace="http://tempuri.org/", Order=0)]
        public ProcScribeOutlook.StruktMain.selectTaskRequestBody Body;
        
        public selectTaskRequest() {
        }
        
        public selectTaskRequest(ProcScribeOutlook.StruktMain.selectTaskRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class selectTaskRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strTaskID;
        
        public selectTaskRequestBody() {
        }
        
        public selectTaskRequestBody(string strTaskID) {
            this.strTaskID = strTaskID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class selectTaskResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="selectTaskResponse", Namespace="http://tempuri.org/", Order=0)]
        public ProcScribeOutlook.StruktMain.selectTaskResponseBody Body;
        
        public selectTaskResponse() {
        }
        
        public selectTaskResponse(ProcScribeOutlook.StruktMain.selectTaskResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class selectTaskResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string selectTaskResult;
        
        public selectTaskResponseBody() {
        }
        
        public selectTaskResponseBody(string selectTaskResult) {
            this.selectTaskResult = selectTaskResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addTaskRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addTask", Namespace="http://tempuri.org/", Order=0)]
        public ProcScribeOutlook.StruktMain.addTaskRequestBody Body;
        
        public addTaskRequest() {
        }
        
        public addTaskRequest(ProcScribeOutlook.StruktMain.addTaskRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class addTaskRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strTaskObject;
        
        public addTaskRequestBody() {
        }
        
        public addTaskRequestBody(string strTaskObject) {
            this.strTaskObject = strTaskObject;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addTaskResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addTaskResponse", Namespace="http://tempuri.org/", Order=0)]
        public ProcScribeOutlook.StruktMain.addTaskResponseBody Body;
        
        public addTaskResponse() {
        }
        
        public addTaskResponse(ProcScribeOutlook.StruktMain.addTaskResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class addTaskResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string addTaskResult;
        
        public addTaskResponseBody() {
        }
        
        public addTaskResponseBody(string addTaskResult) {
            this.addTaskResult = addTaskResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class editTaskRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="editTask", Namespace="http://tempuri.org/", Order=0)]
        public ProcScribeOutlook.StruktMain.editTaskRequestBody Body;
        
        public editTaskRequest() {
        }
        
        public editTaskRequest(ProcScribeOutlook.StruktMain.editTaskRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class editTaskRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strTask;
        
        public editTaskRequestBody() {
        }
        
        public editTaskRequestBody(string strTask) {
            this.strTask = strTask;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class editTaskResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="editTaskResponse", Namespace="http://tempuri.org/", Order=0)]
        public ProcScribeOutlook.StruktMain.editTaskResponseBody Body;
        
        public editTaskResponse() {
        }
        
        public editTaskResponse(ProcScribeOutlook.StruktMain.editTaskResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class editTaskResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string editTaskResult;
        
        public editTaskResponseBody() {
        }
        
        public editTaskResponseBody(string editTaskResult) {
            this.editTaskResult = editTaskResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class deleteTaskRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="deleteTask", Namespace="http://tempuri.org/", Order=0)]
        public ProcScribeOutlook.StruktMain.deleteTaskRequestBody Body;
        
        public deleteTaskRequest() {
        }
        
        public deleteTaskRequest(ProcScribeOutlook.StruktMain.deleteTaskRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class deleteTaskRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strTaskID;
        
        public deleteTaskRequestBody() {
        }
        
        public deleteTaskRequestBody(string strTaskID) {
            this.strTaskID = strTaskID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class deleteTaskResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="deleteTaskResponse", Namespace="http://tempuri.org/", Order=0)]
        public ProcScribeOutlook.StruktMain.deleteTaskResponseBody Body;
        
        public deleteTaskResponse() {
        }
        
        public deleteTaskResponse(ProcScribeOutlook.StruktMain.deleteTaskResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class deleteTaskResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string deleteTaskResult;
        
        public deleteTaskResponseBody() {
        }
        
        public deleteTaskResponseBody(string deleteTaskResult) {
            this.deleteTaskResult = deleteTaskResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class selectTaskProcessAllRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="selectTaskProcessAll", Namespace="http://tempuri.org/", Order=0)]
        public ProcScribeOutlook.StruktMain.selectTaskProcessAllRequestBody Body;
        
        public selectTaskProcessAllRequest() {
        }
        
        public selectTaskProcessAllRequest(ProcScribeOutlook.StruktMain.selectTaskProcessAllRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class selectTaskProcessAllRequestBody {
        
        public selectTaskProcessAllRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class selectTaskProcessAllResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="selectTaskProcessAllResponse", Namespace="http://tempuri.org/", Order=0)]
        public ProcScribeOutlook.StruktMain.selectTaskProcessAllResponseBody Body;
        
        public selectTaskProcessAllResponse() {
        }
        
        public selectTaskProcessAllResponse(ProcScribeOutlook.StruktMain.selectTaskProcessAllResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class selectTaskProcessAllResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string selectTaskProcessAllResult;
        
        public selectTaskProcessAllResponseBody() {
        }
        
        public selectTaskProcessAllResponseBody(string selectTaskProcessAllResult) {
            this.selectTaskProcessAllResult = selectTaskProcessAllResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class selectTaskByParentWorkflowIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="selectTaskByParentWorkflowID", Namespace="http://tempuri.org/", Order=0)]
        public ProcScribeOutlook.StruktMain.selectTaskByParentWorkflowIDRequestBody Body;
        
        public selectTaskByParentWorkflowIDRequest() {
        }
        
        public selectTaskByParentWorkflowIDRequest(ProcScribeOutlook.StruktMain.selectTaskByParentWorkflowIDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class selectTaskByParentWorkflowIDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strParentWorkflowID;
        
        public selectTaskByParentWorkflowIDRequestBody() {
        }
        
        public selectTaskByParentWorkflowIDRequestBody(string strParentWorkflowID) {
            this.strParentWorkflowID = strParentWorkflowID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class selectTaskByParentWorkflowIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="selectTaskByParentWorkflowIDResponse", Namespace="http://tempuri.org/", Order=0)]
        public ProcScribeOutlook.StruktMain.selectTaskByParentWorkflowIDResponseBody Body;
        
        public selectTaskByParentWorkflowIDResponse() {
        }
        
        public selectTaskByParentWorkflowIDResponse(ProcScribeOutlook.StruktMain.selectTaskByParentWorkflowIDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class selectTaskByParentWorkflowIDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string selectTaskByParentWorkflowIDResult;
        
        public selectTaskByParentWorkflowIDResponseBody() {
        }
        
        public selectTaskByParentWorkflowIDResponseBody(string selectTaskByParentWorkflowIDResult) {
            this.selectTaskByParentWorkflowIDResult = selectTaskByParentWorkflowIDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class selectTaskByUserIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="selectTaskByUserID", Namespace="http://tempuri.org/", Order=0)]
        public ProcScribeOutlook.StruktMain.selectTaskByUserIDRequestBody Body;
        
        public selectTaskByUserIDRequest() {
        }
        
        public selectTaskByUserIDRequest(ProcScribeOutlook.StruktMain.selectTaskByUserIDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class selectTaskByUserIDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strUserID;
        
        public selectTaskByUserIDRequestBody() {
        }
        
        public selectTaskByUserIDRequestBody(string strUserID) {
            this.strUserID = strUserID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class selectTaskByUserIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="selectTaskByUserIDResponse", Namespace="http://tempuri.org/", Order=0)]
        public ProcScribeOutlook.StruktMain.selectTaskByUserIDResponseBody Body;
        
        public selectTaskByUserIDResponse() {
        }
        
        public selectTaskByUserIDResponse(ProcScribeOutlook.StruktMain.selectTaskByUserIDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class selectTaskByUserIDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string selectTaskByUserIDResult;
        
        public selectTaskByUserIDResponseBody() {
        }
        
        public selectTaskByUserIDResponseBody(string selectTaskByUserIDResult) {
            this.selectTaskByUserIDResult = selectTaskByUserIDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getFileListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getFileList", Namespace="http://tempuri.org/", Order=0)]
        public ProcScribeOutlook.StruktMain.getFileListRequestBody Body;
        
        public getFileListRequest() {
        }
        
        public getFileListRequest(ProcScribeOutlook.StruktMain.getFileListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getFileListRequestBody {
        
        public getFileListRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getFileListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getFileListResponse", Namespace="http://tempuri.org/", Order=0)]
        public ProcScribeOutlook.StruktMain.getFileListResponseBody Body;
        
        public getFileListResponse() {
        }
        
        public getFileListResponse(ProcScribeOutlook.StruktMain.getFileListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getFileListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getFileListResult;
        
        public getFileListResponseBody() {
        }
        
        public getFileListResponseBody(string getFileListResult) {
            this.getFileListResult = getFileListResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface StruktMainSoapChannel : ProcScribeOutlook.StruktMain.StruktMainSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StruktMainSoapClient : System.ServiceModel.ClientBase<ProcScribeOutlook.StruktMain.StruktMainSoap>, ProcScribeOutlook.StruktMain.StruktMainSoap {
        
        public StruktMainSoapClient() {
        }
        
        public StruktMainSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StruktMainSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StruktMainSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StruktMainSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProcScribeOutlook.StruktMain.selectWorkflowResponse ProcScribeOutlook.StruktMain.StruktMainSoap.selectWorkflow(ProcScribeOutlook.StruktMain.selectWorkflowRequest request) {
            return base.Channel.selectWorkflow(request);
        }
        
        public string selectWorkflow(string strWorkflowID) {
            ProcScribeOutlook.StruktMain.selectWorkflowRequest inValue = new ProcScribeOutlook.StruktMain.selectWorkflowRequest();
            inValue.Body = new ProcScribeOutlook.StruktMain.selectWorkflowRequestBody();
            inValue.Body.strWorkflowID = strWorkflowID;
            ProcScribeOutlook.StruktMain.selectWorkflowResponse retVal = ((ProcScribeOutlook.StruktMain.StruktMainSoap)(this)).selectWorkflow(inValue);
            return retVal.Body.selectWorkflowResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProcScribeOutlook.StruktMain.addStruktProcessResponse ProcScribeOutlook.StruktMain.StruktMainSoap.addStruktProcess(ProcScribeOutlook.StruktMain.addStruktProcessRequest request) {
            return base.Channel.addStruktProcess(request);
        }
        
        public string addStruktProcess(string strProcessName) {
            ProcScribeOutlook.StruktMain.addStruktProcessRequest inValue = new ProcScribeOutlook.StruktMain.addStruktProcessRequest();
            inValue.Body = new ProcScribeOutlook.StruktMain.addStruktProcessRequestBody();
            inValue.Body.strProcessName = strProcessName;
            ProcScribeOutlook.StruktMain.addStruktProcessResponse retVal = ((ProcScribeOutlook.StruktMain.StruktMainSoap)(this)).addStruktProcess(inValue);
            return retVal.Body.addStruktProcessResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProcScribeOutlook.StruktMain.editStruktProcessNameResponse ProcScribeOutlook.StruktMain.StruktMainSoap.editStruktProcessName(ProcScribeOutlook.StruktMain.editStruktProcessNameRequest request) {
            return base.Channel.editStruktProcessName(request);
        }
        
        public string editStruktProcessName(int strStruktProcessID, string strStruktProcessName) {
            ProcScribeOutlook.StruktMain.editStruktProcessNameRequest inValue = new ProcScribeOutlook.StruktMain.editStruktProcessNameRequest();
            inValue.Body = new ProcScribeOutlook.StruktMain.editStruktProcessNameRequestBody();
            inValue.Body.strStruktProcessID = strStruktProcessID;
            inValue.Body.strStruktProcessName = strStruktProcessName;
            ProcScribeOutlook.StruktMain.editStruktProcessNameResponse retVal = ((ProcScribeOutlook.StruktMain.StruktMainSoap)(this)).editStruktProcessName(inValue);
            return retVal.Body.editStruktProcessNameResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProcScribeOutlook.StruktMain.deleteStruktProcessResponse ProcScribeOutlook.StruktMain.StruktMainSoap.deleteStruktProcess(ProcScribeOutlook.StruktMain.deleteStruktProcessRequest request) {
            return base.Channel.deleteStruktProcess(request);
        }
        
        public string deleteStruktProcess(int intStruktProcessID) {
            ProcScribeOutlook.StruktMain.deleteStruktProcessRequest inValue = new ProcScribeOutlook.StruktMain.deleteStruktProcessRequest();
            inValue.Body = new ProcScribeOutlook.StruktMain.deleteStruktProcessRequestBody();
            inValue.Body.intStruktProcessID = intStruktProcessID;
            ProcScribeOutlook.StruktMain.deleteStruktProcessResponse retVal = ((ProcScribeOutlook.StruktMain.StruktMainSoap)(this)).deleteStruktProcess(inValue);
            return retVal.Body.deleteStruktProcessResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProcScribeOutlook.StruktMain.addWorkflowResponse ProcScribeOutlook.StruktMain.StruktMainSoap.addWorkflow(ProcScribeOutlook.StruktMain.addWorkflowRequest request) {
            return base.Channel.addWorkflow(request);
        }
        
        public string addWorkflow() {
            ProcScribeOutlook.StruktMain.addWorkflowRequest inValue = new ProcScribeOutlook.StruktMain.addWorkflowRequest();
            inValue.Body = new ProcScribeOutlook.StruktMain.addWorkflowRequestBody();
            ProcScribeOutlook.StruktMain.addWorkflowResponse retVal = ((ProcScribeOutlook.StruktMain.StruktMainSoap)(this)).addWorkflow(inValue);
            return retVal.Body.addWorkflowResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProcScribeOutlook.StruktMain.editWorkflowResponse ProcScribeOutlook.StruktMain.StruktMainSoap.editWorkflow(ProcScribeOutlook.StruktMain.editWorkflowRequest request) {
            return base.Channel.editWorkflow(request);
        }
        
        public string editWorkflow(string strWorkflow) {
            ProcScribeOutlook.StruktMain.editWorkflowRequest inValue = new ProcScribeOutlook.StruktMain.editWorkflowRequest();
            inValue.Body = new ProcScribeOutlook.StruktMain.editWorkflowRequestBody();
            inValue.Body.strWorkflow = strWorkflow;
            ProcScribeOutlook.StruktMain.editWorkflowResponse retVal = ((ProcScribeOutlook.StruktMain.StruktMainSoap)(this)).editWorkflow(inValue);
            return retVal.Body.editWorkflowResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProcScribeOutlook.StruktMain.deleteWorkflowResponse ProcScribeOutlook.StruktMain.StruktMainSoap.deleteWorkflow(ProcScribeOutlook.StruktMain.deleteWorkflowRequest request) {
            return base.Channel.deleteWorkflow(request);
        }
        
        public string deleteWorkflow(string strWorkflowID) {
            ProcScribeOutlook.StruktMain.deleteWorkflowRequest inValue = new ProcScribeOutlook.StruktMain.deleteWorkflowRequest();
            inValue.Body = new ProcScribeOutlook.StruktMain.deleteWorkflowRequestBody();
            inValue.Body.strWorkflowID = strWorkflowID;
            ProcScribeOutlook.StruktMain.deleteWorkflowResponse retVal = ((ProcScribeOutlook.StruktMain.StruktMainSoap)(this)).deleteWorkflow(inValue);
            return retVal.Body.deleteWorkflowResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProcScribeOutlook.StruktMain.selectTaskResponse ProcScribeOutlook.StruktMain.StruktMainSoap.selectTask(ProcScribeOutlook.StruktMain.selectTaskRequest request) {
            return base.Channel.selectTask(request);
        }
        
        public string selectTask(string strTaskID) {
            ProcScribeOutlook.StruktMain.selectTaskRequest inValue = new ProcScribeOutlook.StruktMain.selectTaskRequest();
            inValue.Body = new ProcScribeOutlook.StruktMain.selectTaskRequestBody();
            inValue.Body.strTaskID = strTaskID;
            ProcScribeOutlook.StruktMain.selectTaskResponse retVal = ((ProcScribeOutlook.StruktMain.StruktMainSoap)(this)).selectTask(inValue);
            return retVal.Body.selectTaskResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProcScribeOutlook.StruktMain.addTaskResponse ProcScribeOutlook.StruktMain.StruktMainSoap.addTask(ProcScribeOutlook.StruktMain.addTaskRequest request) {
            return base.Channel.addTask(request);
        }
        
        public string addTask(string strTaskObject) {
            ProcScribeOutlook.StruktMain.addTaskRequest inValue = new ProcScribeOutlook.StruktMain.addTaskRequest();
            inValue.Body = new ProcScribeOutlook.StruktMain.addTaskRequestBody();
            inValue.Body.strTaskObject = strTaskObject;
            ProcScribeOutlook.StruktMain.addTaskResponse retVal = ((ProcScribeOutlook.StruktMain.StruktMainSoap)(this)).addTask(inValue);
            return retVal.Body.addTaskResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProcScribeOutlook.StruktMain.editTaskResponse ProcScribeOutlook.StruktMain.StruktMainSoap.editTask(ProcScribeOutlook.StruktMain.editTaskRequest request) {
            return base.Channel.editTask(request);
        }
        
        public string editTask(string strTask) {
            ProcScribeOutlook.StruktMain.editTaskRequest inValue = new ProcScribeOutlook.StruktMain.editTaskRequest();
            inValue.Body = new ProcScribeOutlook.StruktMain.editTaskRequestBody();
            inValue.Body.strTask = strTask;
            ProcScribeOutlook.StruktMain.editTaskResponse retVal = ((ProcScribeOutlook.StruktMain.StruktMainSoap)(this)).editTask(inValue);
            return retVal.Body.editTaskResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProcScribeOutlook.StruktMain.deleteTaskResponse ProcScribeOutlook.StruktMain.StruktMainSoap.deleteTask(ProcScribeOutlook.StruktMain.deleteTaskRequest request) {
            return base.Channel.deleteTask(request);
        }
        
        public string deleteTask(string strTaskID) {
            ProcScribeOutlook.StruktMain.deleteTaskRequest inValue = new ProcScribeOutlook.StruktMain.deleteTaskRequest();
            inValue.Body = new ProcScribeOutlook.StruktMain.deleteTaskRequestBody();
            inValue.Body.strTaskID = strTaskID;
            ProcScribeOutlook.StruktMain.deleteTaskResponse retVal = ((ProcScribeOutlook.StruktMain.StruktMainSoap)(this)).deleteTask(inValue);
            return retVal.Body.deleteTaskResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProcScribeOutlook.StruktMain.selectTaskProcessAllResponse ProcScribeOutlook.StruktMain.StruktMainSoap.selectTaskProcessAll(ProcScribeOutlook.StruktMain.selectTaskProcessAllRequest request) {
            return base.Channel.selectTaskProcessAll(request);
        }
        
        public string selectTaskProcessAll() {
            ProcScribeOutlook.StruktMain.selectTaskProcessAllRequest inValue = new ProcScribeOutlook.StruktMain.selectTaskProcessAllRequest();
            inValue.Body = new ProcScribeOutlook.StruktMain.selectTaskProcessAllRequestBody();
            ProcScribeOutlook.StruktMain.selectTaskProcessAllResponse retVal = ((ProcScribeOutlook.StruktMain.StruktMainSoap)(this)).selectTaskProcessAll(inValue);
            return retVal.Body.selectTaskProcessAllResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProcScribeOutlook.StruktMain.selectTaskByParentWorkflowIDResponse ProcScribeOutlook.StruktMain.StruktMainSoap.selectTaskByParentWorkflowID(ProcScribeOutlook.StruktMain.selectTaskByParentWorkflowIDRequest request) {
            return base.Channel.selectTaskByParentWorkflowID(request);
        }
        
        public string selectTaskByParentWorkflowID(string strParentWorkflowID) {
            ProcScribeOutlook.StruktMain.selectTaskByParentWorkflowIDRequest inValue = new ProcScribeOutlook.StruktMain.selectTaskByParentWorkflowIDRequest();
            inValue.Body = new ProcScribeOutlook.StruktMain.selectTaskByParentWorkflowIDRequestBody();
            inValue.Body.strParentWorkflowID = strParentWorkflowID;
            ProcScribeOutlook.StruktMain.selectTaskByParentWorkflowIDResponse retVal = ((ProcScribeOutlook.StruktMain.StruktMainSoap)(this)).selectTaskByParentWorkflowID(inValue);
            return retVal.Body.selectTaskByParentWorkflowIDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProcScribeOutlook.StruktMain.selectTaskByUserIDResponse ProcScribeOutlook.StruktMain.StruktMainSoap.selectTaskByUserID(ProcScribeOutlook.StruktMain.selectTaskByUserIDRequest request) {
            return base.Channel.selectTaskByUserID(request);
        }
        
        public string selectTaskByUserID(string strUserID) {
            ProcScribeOutlook.StruktMain.selectTaskByUserIDRequest inValue = new ProcScribeOutlook.StruktMain.selectTaskByUserIDRequest();
            inValue.Body = new ProcScribeOutlook.StruktMain.selectTaskByUserIDRequestBody();
            inValue.Body.strUserID = strUserID;
            ProcScribeOutlook.StruktMain.selectTaskByUserIDResponse retVal = ((ProcScribeOutlook.StruktMain.StruktMainSoap)(this)).selectTaskByUserID(inValue);
            return retVal.Body.selectTaskByUserIDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProcScribeOutlook.StruktMain.getFileListResponse ProcScribeOutlook.StruktMain.StruktMainSoap.getFileList(ProcScribeOutlook.StruktMain.getFileListRequest request) {
            return base.Channel.getFileList(request);
        }
        
        public string getFileList() {
            ProcScribeOutlook.StruktMain.getFileListRequest inValue = new ProcScribeOutlook.StruktMain.getFileListRequest();
            inValue.Body = new ProcScribeOutlook.StruktMain.getFileListRequestBody();
            ProcScribeOutlook.StruktMain.getFileListResponse retVal = ((ProcScribeOutlook.StruktMain.StruktMainSoap)(this)).getFileList(inValue);
            return retVal.Body.getFileListResult;
        }
    }
}
